### PR TITLE
Website Names

### PR DESCRIPTION
**Pull request by samtimmins**
Changed File Names

### CODE REVIEW

**Comment by kierhickey** [comment]
Your commit changes the names but does not remove the old files. also the home.html should be index.html (as this is what will be served by the root directory.

**Comment by kierhickey** [comment]
@samtimmins I'll fix it and push it.

**Comment by samtimmins** [comment]
Ok, maybe that is for the best, I think I better hit up the documentation again, I'm confusing myself :P

**Comment by kierhickey** [comment]
The Pull request you just did is correct, however you pushed your dev branch

**Pull request merged**
